### ISSUE TITLE
The flake cannot be used

### ISSUE THREAD

**Issue by luisnquin** [redyf/font-flake#1]
# Screenshot of the problem

![image](https://github.com/user-attachments/assets/4264fccd-86d1-45b5-8327-efa394d61b6e)

If this flake is only for personal use is fine for me.

**Comment by redyf** [comment]
Some fonts (MonoLisa, Berkeley and Cartograph) require a personal ssh key because they are paid. If you wish to use a specific free font, change the input package or make a fork to install the font you want.

**Comment by luisnquin** [comment]
Understood, thanks.
